@echo off
color 0a
title Quest Journal Test
cls
:top
set textp1=                                                            
set textp2=                                                            
set textp3=                                                            
set textp4=                                                            
set textp5=                                                            
set /p text=< Quest\Rat_Extermination\Qdescription
set textp1=%text:~0,50%
if "%textp1:~1,1%"=="-" (
GOTO textset2
)
if "%textp1:~2,1%"=="-" (
GOTO textset2
)
if "%textp1:~3,1%"=="-" (
GOTO textset2
)
if "%textp1:~4,1%"=="-" (
GOTO textset2
)
if "%textp1:~5,1%"=="-" (
GOTO textset2
)
if "%textp1:~6,1%"=="-" (
GOTO textset2
)
if "%textp1:~7,1%"=="-" (
GOTO textset2
)
if "%textp1:~8,1%"=="-" (
GOTO textset2
)
if "%textp1:~9,1%"=="-" (
GOTO textset2
)
if "%textp1:~10,1%"=="-" (
GOTO textset2
)
if "%textp1:~11,1%"=="-" (
GOTO textset2
)
if "%textp1:~12,1%"=="-" (
GOTO textset2
)
if "%textp1:~13,1%"=="-" (
GOTO textset2
)
if "%textp1:~14,1%"=="-" (
GOTO textset2
)
if "%textp1:~15,1%"=="-" (
GOTO textset2
)
if "%textp1:~16,1%"=="-" (
GOTO textset2
)
if "%textp1:~17,1%"=="-" (
GOTO textset2
)
if "%textp1:~18,1%"=="-" (
GOTO textset2
)
if "%textp1:~19,1%"=="-" (
GOTO textset2
)
if "%textp1:~20,1%"=="-" (
GOTO textset2
)
if "%textp1:~21,1%"=="-" (
GOTO textset2
)
if "%textp1:~22,1%"=="-" (
GOTO textset2
)
if "%textp1:~23,1%"=="-" (
GOTO textset2
)
if "%textp1:~24,1%"=="-" (
GOTO textset2
)
if "%textp1:~25,1%"=="-" (
GOTO textset2
)
if "%textp1:~26,1%"=="-" (
GOTO textset2
)
if "%textp1:~27,1%"=="-" (
GOTO textset2
)
if "%textp1:~28,1%"=="-" (
GOTO textset2
)
if "%textp1:~29,1%"=="-" (
GOTO textset2
)
if "%textp1:~30,1%"=="-" (
GOTO textset2
)
if "%textp1:~31,1%"=="-" (
GOTO textset2
)
if "%textp1:~32,1%"=="-" (
GOTO textset2
)
if "%textp1:~33,1%"=="-" (
GOTO textset2
)
if "%textp1:~34,1%"=="-" (
GOTO textset2
)
if "%textp1:~35,1%"=="-" (
GOTO textset2
)
if "%textp1:~36,1%"=="-" (
GOTO textset2
)
if "%textp1:~37,1%"=="-" (
GOTO textset2
)
if "%textp1:~38,1%"=="-" (
GOTO textset2
)
if "%textp1:~39,1%"=="-" (
GOTO textset2
)
if "%textp1:~40,1%"=="-" (
GOTO textset2
)
if "%textp1:~41,1%"=="-" (
GOTO textset2
)
if "%textp1:~42,1%"=="-" (
GOTO textset2
)
if "%textp1:~43,1%"=="-" (
GOTO textset2
)
if "%textp1:~44,1%"=="-" (
GOTO textset2
)
if "%textp1:~45,1%"=="-" (
GOTO textset2
)
if "%textp1:~46,1%"=="-" (
GOTO textset2
)
if "%textp1:~47,1%"=="-" (
GOTO textset2
)
if "%textp1:~48,1%"=="-" (
GOTO textset2
)
if "%textp1:~49,1%"=="-" (
GOTO textset2
)
set textp2=%text:~50,50%
if "%textp2:~1,1%"=="-" (
GOTO textset2
)
if "%textp2:~2,1%"=="-" (
GOTO textset2
)
if "%textp2:~3,1%"=="-" (
GOTO textset2
)
if "%textp2:~4,1%"=="-" (
GOTO textset2
)
if "%textp2:~5,1%"=="-" (
GOTO textset2
)
if "%textp2:~6,1%"=="-" (
GOTO textset2
)
if "%textp2:~7,1%"=="-" (
GOTO textset2
)
if "%textp2:~8,1%"=="-" (
GOTO textset2
)
if "%textp2:~9,1%"=="-" (
GOTO textset2
)
if "%textp2:~10,1%"=="-" (
GOTO textset2
)
if "%textp2:~11,1%"=="-" (
GOTO textset2
)
if "%textp2:~12,1%"=="-" (
GOTO textset2
)
if "%textp2:~13,1%"=="-" (
GOTO textset2
)
if "%textp2:~14,1%"=="-" (
GOTO textset2
)
if "%textp2:~15,1%"=="-" (
GOTO textset2
)
if "%textp2:~16,1%"=="-" (
GOTO textset2
)
if "%textp2:~17,1%"=="-" (
GOTO textset2
)
if "%textp2:~18,1%"=="-" (
GOTO textset2
)
if "%textp2:~19,1%"=="-" (
GOTO textset2
)
if "%textp2:~20,1%"=="-" (
GOTO textset2
)
if "%textp2:~21,1%"=="-" (
GOTO textset2
)
if "%textp2:~22,1%"=="-" (
GOTO textset2
)
if "%textp2:~23,1%"=="-" (
GOTO textset2
)
if "%textp2:~24,1%"=="-" (
GOTO textset2
)
if "%textp2:~25,1%"=="-" (
GOTO textset2
)
if "%textp2:~26,1%"=="-" (
GOTO textset2
)
if "%textp2:~27,1%"=="-" (
GOTO textset2
)
if "%textp2:~28,1%"=="-" (
GOTO textset2
)
if "%textp2:~29,1%"=="-" (
GOTO textset2
)
if "%textp2:~30,1%"=="-" (
GOTO textset2
)
if "%textp2:~31,1%"=="-" (
GOTO textset2
)
if "%textp2:~32,1%"=="-" (
GOTO textset2
)
if "%textp2:~33,1%"=="-" (
GOTO textset2
)
if "%textp2:~34,1%"=="-" (
GOTO textset2
)
if "%textp2:~35,1%"=="-" (
GOTO textset2
)
if "%textp2:~36,1%"=="-" (
GOTO textset2
)
if "%textp2:~37,1%"=="-" (
GOTO textset2
)
if "%textp2:~38,1%"=="-" (
GOTO textset2
)
if "%textp2:~39,1%"=="-" (
GOTO textset2
)
if "%textp2:~40,1%"=="-" (
GOTO textset2
)
if "%textp2:~41,1%"=="-" (
GOTO textset2
)
if "%textp2:~42,1%"=="-" (
GOTO textset2
)
if "%textp2:~43,1%"=="-" (
GOTO textset2
)
if "%textp2:~44,1%"=="-" (
GOTO textset2
)
if "%textp2:~45,1%"=="-" (
GOTO textset2
)
if "%textp2:~46,1%"=="-" (
GOTO textset2
)
if "%textp2:~47,1%"=="-" (
GOTO textset2
)
if "%textp2:~48,1%"=="-" (
GOTO textset2
)
if "%textp2:~49,1%"=="-" (
GOTO textset2
)
set textp3=%text:~100,50%
if "%textp3:~1,1%"=="-" (
GOTO textset2
)
if "%textp3:~2,1%"=="-" (
GOTO textset2
)
if "%textp3:~3,1%"=="-" (
GOTO textset2
)
if "%textp3:~4,1%"=="-" (
GOTO textset2
)
if "%textp3:~5,1%"=="-" (
GOTO textset2
)
if "%textp3:~6,1%"=="-" (
GOTO textset2
)
if "%textp3:~7,1%"=="-" (
GOTO textset2
)
if "%textp3:~8,1%"=="-" (
GOTO textset2
)
if "%textp3:~9,1%"=="-" (
GOTO textset2
)
if "%textp3:~10,1%"=="-" (
GOTO textset2
)
if "%textp3:~11,1%"=="-" (
GOTO textset2
)
if "%textp3:~12,1%"=="-" (
GOTO textset2
)
if "%textp3:~13,1%"=="-" (
GOTO textset2
)
if "%textp3:~14,1%"=="-" (
GOTO textset2
)
if "%textp3:~15,1%"=="-" (
GOTO textset2
)
if "%textp3:~16,1%"=="-" (
GOTO textset2
)
if "%textp3:~17,1%"=="-" (
GOTO textset2
)
if "%textp3:~18,1%"=="-" (
GOTO textset2
)
if "%textp3:~19,1%"=="-" (
GOTO textset2
)
if "%textp3:~20,1%"=="-" (
GOTO textset2
)
if "%textp3:~21,1%"=="-" (
GOTO textset2
)
if "%textp3:~22,1%"=="-" (
GOTO textset2
)
if "%textp3:~23,1%"=="-" (
GOTO textset2
)
if "%textp3:~24,1%"=="-" (
GOTO textset2
)
if "%textp3:~25,1%"=="-" (
GOTO textset2
)
if "%textp3:~26,1%"=="-" (
GOTO textset2
)
if "%textp3:~27,1%"=="-" (
GOTO textset2
)
if "%textp3:~28,1%"=="-" (
GOTO textset2
)
if "%textp3:~29,1%"=="-" (
GOTO textset2
)
if "%textp3:~30,1%"=="-" (
GOTO textset2
)
if "%textp3:~31,1%"=="-" (
GOTO textset2
)
if "%textp3:~32,1%"=="-" (
GOTO textset2
)
if "%textp3:~33,1%"=="-" (
GOTO textset2
)
if "%textp3:~34,1%"=="-" (
GOTO textset2
)
if "%textp3:~35,1%"=="-" (
GOTO textset2
)
if "%textp3:~36,1%"=="-" (
GOTO textset2
)
if "%textp3:~37,1%"=="-" (
GOTO textset2
)
if "%textp3:~38,1%"=="-" (
GOTO textset2
)
if "%textp3:~39,1%"=="-" (
GOTO textset2
)
if "%textp3:~40,1%"=="-" (
GOTO textset2
)
if "%textp3:~41,1%"=="-" (
GOTO textset2
)
if "%textp3:~42,1%"=="-" (
GOTO textset2
)
if "%textp3:~43,1%"=="-" (
GOTO textset2
)
if "%textp3:~44,1%"=="-" (
GOTO textset2
)
if "%textp3:~45,1%"=="-" (
GOTO textset2
)
if "%textp3:~46,1%"=="-" (
GOTO textset2
)
if "%textp3:~47,1%"=="-" (
GOTO textset2
)
if "%textp3:~48,1%"=="-" (
GOTO textset2
)
if "%textp3:~49,1%"=="-" (
GOTO textset2
)
set textp4=%text:~150,50%
if "%textp4:~1,1%"=="-" (
GOTO textset2
)
if "%textp4:~2,1%"=="-" (
GOTO textset2
)
if "%textp4:~3,1%"=="-" (
GOTO textset2
)
if "%textp4:~4,1%"=="-" (
GOTO textset2
)
if "%textp4:~5,1%"=="-" (
GOTO textset2
)
if "%textp4:~6,1%"=="-" (
GOTO textset2
)
if "%textp4:~7,1%"=="-" (
GOTO textset2
)
if "%textp4:~8,1%"=="-" (
GOTO textset2
)
if "%textp4:~9,1%"=="-" (
GOTO textset2
)
if "%textp4:~10,1%"=="-" (
GOTO textset2
)
if "%textp4:~11,1%"=="-" (
GOTO textset2
)
if "%textp4:~12,1%"=="-" (
GOTO textset2
)
if "%textp4:~13,1%"=="-" (
GOTO textset2
)
if "%textp4:~14,1%"=="-" (
GOTO textset2
)
if "%textp4:~15,1%"=="-" (
GOTO textset2
)
if "%textp4:~16,1%"=="-" (
GOTO textset2
)
if "%textp4:~17,1%"=="-" (
GOTO textset2
)
if "%textp4:~18,1%"=="-" (
GOTO textset2
)
if "%textp4:~19,1%"=="-" (
GOTO textset2
)
if "%textp4:~20,1%"=="-" (
GOTO textset2
)
if "%textp4:~21,1%"=="-" (
GOTO textset2
)
if "%textp4:~22,1%"=="-" (
GOTO textset2
)
if "%textp4:~23,1%"=="-" (
GOTO textset2
)
if "%textp4:~24,1%"=="-" (
GOTO textset2
)
if "%textp4:~25,1%"=="-" (
GOTO textset2
)
if "%textp4:~26,1%"=="-" (
GOTO textset2
)
if "%textp4:~27,1%"=="-" (
GOTO textset2
)
if "%textp4:~28,1%"=="-" (
GOTO textset2
)
if "%textp4:~29,1%"=="-" (
GOTO textset2
)
if "%textp4:~30,1%"=="-" (
GOTO textset2
)
if "%textp4:~31,1%"=="-" (
GOTO textset2
)
if "%textp4:~32,1%"=="-" (
GOTO textset2
)
if "%textp4:~33,1%"=="-" (
GOTO textset2
)
if "%textp4:~34,1%"=="-" (
GOTO textset2
)
if "%textp4:~35,1%"=="-" (
GOTO textset2
)
if "%textp4:~36,1%"=="-" (
GOTO textset2
)
if "%textp4:~37,1%"=="-" (
GOTO textset2
)
if "%textp4:~38,1%"=="-" (
GOTO textset2
)
if "%textp4:~39,1%"=="-" (
GOTO textset2
)
if "%textp4:~40,1%"=="-" (
GOTO textset2
)
if "%textp4:~41,1%"=="-" (
GOTO textset2
)
if "%textp4:~42,1%"=="-" (
GOTO textset2
)
if "%textp4:~43,1%"=="-" (
GOTO textset2
)
if "%textp4:~44,1%"=="-" (
GOTO textset2
)
if "%textp4:~45,1%"=="-" (
GOTO textset2
)
if "%textp4:~46,1%"=="-" (
GOTO textset2
)
if "%textp4:~47,1%"=="-" (
GOTO textset2
)
if "%textp4:~48,1%"=="-" (
GOTO textset2
)
if "%textp4:~49,1%"=="-" (
GOTO textset2
)
set textp5=%text:~200,50%
if "%textp5:~1,1%"=="-" (
GOTO textset2
)
if "%textp5:~2,1%"=="-" (
GOTO textset2
)
if "%textp5:~3,1%"=="-" (
GOTO textset2
)
if "%textp5:~4,1%"=="-" (
GOTO textset2
)
if "%textp5:~5,1%"=="-" (
GOTO textset2
)
if "%textp5:~6,1%"=="-" (
GOTO textset2
)
if "%textp5:~7,1%"=="-" (
GOTO textset2
)
if "%textp5:~8,1%"=="-" (
GOTO textset2
)
if "%textp5:~9,1%"=="-" (
GOTO textset2
)
if "%textp5:~10,1%"=="-" (
GOTO textset2
)
if "%textp5:~11,1%"=="-" (
GOTO textset2
)
if "%textp5:~12,1%"=="-" (
GOTO textset2
)
if "%textp5:~13,1%"=="-" (
GOTO textset2
)
if "%textp5:~14,1%"=="-" (
GOTO textset2
)
if "%textp5:~15,1%"=="-" (
GOTO textset2
)
if "%textp5:~16,1%"=="-" (
GOTO textset2
)
if "%textp5:~17,1%"=="-" (
GOTO textset2
)
if "%textp5:~18,1%"=="-" (
GOTO textset2
)
if "%textp5:~19,1%"=="-" (
GOTO textset2
)
if "%textp5:~20,1%"=="-" (
GOTO textset2
)
if "%textp5:~21,1%"=="-" (
GOTO textset2
)
if "%textp5:~22,1%"=="-" (
GOTO textset2
)
if "%textp5:~23,1%"=="-" (
GOTO textset2
)
if "%textp5:~24,1%"=="-" (
GOTO textset2
)
if "%textp5:~25,1%"=="-" (
GOTO textset2
)
if "%textp5:~26,1%"=="-" (
GOTO textset2
)
if "%textp5:~27,1%"=="-" (
GOTO textset2
)
if "%textp5:~28,1%"=="-" (
GOTO textset2
)
if "%textp5:~29,1%"=="-" (
GOTO textset2
)
if "%textp5:~30,1%"=="-" (
GOTO textset2
)
if "%textp5:~31,1%"=="-" (
GOTO textset2
)
if "%textp5:~32,1%"=="-" (
GOTO textset2
)
if "%textp5:~33,1%"=="-" (
GOTO textset2
)
if "%textp5:~34,1%"=="-" (
GOTO textset2
)
if "%textp5:~35,1%"=="-" (
GOTO textset2
)
if "%textp5:~36,1%"=="-" (
GOTO textset2
)
if "%textp5:~37,1%"=="-" (
GOTO textset2
)
if "%textp5:~38,1%"=="-" (
GOTO textset2
)
if "%textp5:~39,1%"=="-" (
GOTO textset2
)
if "%textp5:~40,1%"=="-" (
GOTO textset2
)
if "%textp5:~41,1%"=="-" (
GOTO textset2
)
if "%textp5:~42,1%"=="-" (
GOTO textset2
)
if "%textp5:~43,1%"=="-" (
GOTO textset2
)
if "%textp5:~44,1%"=="-" (
GOTO textset2
)
if "%textp5:~45,1%"=="-" (
GOTO textset2
)
if "%textp5:~46,1%"=="-" (
GOTO textset2
)
if "%textp5:~47,1%"=="-" (
GOTO textset2
)
if "%textp5:~48,1%"=="-" (
GOTO textset2
)
if "%textp5:~49,1%"=="-" (
GOTO textset2
)
if "%textp5:~50,1%"=="-" (
GOTO textset2
)
if "%textp5:~51,1%"=="-" (
GOTO textset2
)
if "%textp5:~52,1%"=="-" (
GOTO textset2
)
if "%textp5:~53,1%"=="-" (
GOTO textset2
)
if "%textp5:~54,1%"=="-" (
GOTO textset2
)
if "%textp5:~55,1%"=="-" (
GOTO textset2
)
if "%textp5:~56,1%"=="-" (
GOTO textset2
)
if "%textp5:~57,1%"=="-" (
GOTO textset2
)
if "%textp5:~58,1%"=="-" (
GOTO textset2
)
if "%textp5:~59,1%"=="-" (
GOTO textset2
)
echo FAIL!!!
pause

:textset2
cls
echo  ------------------------------------------------------------------------------
echo  I   {i} - In Progress   I   {c} - Completed   I                              I
echo  I----------------------------------------------------------------------------I
echo  I                       I                                                    I
echo  I                       I Quest Description:                                 I
echo  I                       I                                                    I
echo  I                       I %textp1:~0,50% I
echo  I                       I %textp2:~0,50% I
echo  I                       I %textp3:~0,50% I
echo  I                       I %textp4:~0,50% I
echo  I                       I %textp5:~0,50% I
echo  I                       I                                                    I
echo  I                       I                                                    I
echo  I                       I                                                    I
echo  I                       I                                                    I
echo  I                       I                                                    I
echo  I                       I                                                    I
echo  I                       I                                                    I
echo  I                       I                                                    I
echo  I                       I                                                    I
echo  I                       I                                                    I
echo  ------------------------------------------------------------------------------
echo.
pause
GOTO top





















